# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ba6a101976c8bc4653069a7a1a418b7e90441aec2839ab4c830dfef493dde3b6d3898f71ef8cb215a78e16c08e8329a336440b2974739dc2d5e7ff86593b34

test:
  secret_key_base: 0c82ba6414b5744b3f43ea83d26107624ec7e664ee46f3c86550de871f5e9b8d473d35dc6f357cc07b79a9c75f8d1012f6f65a41d7a178de12b54e98f4391990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
